### ISSUE TITLE
Question about symmetric noise rates.

### ISSUE THREAD

**Issue by YangYang** [penghu-cs/MRL#1]
I recently read your paper and very interested in it. When I reading, I'm confused about how to implement "symmetric noise rates". Code of the paper just provides the path of symmetric noise rates JSON file but not provides the detail of it. 
So could you share the code detail of add noise? Your help will be greatly appreciated.

**Comment by penghu-cs** [comment]
Thanks a lot. The code could be found in Lines 190-220 of src/noisydataset.py.

**Comment by YangYang** [comment]
Thanks for your reply. It's helpful.
