### ISSUE TITLE
Question about Contrastive Learning loss.

### ISSUE THREAD

**Issue by YangYang** [penghu-cs/MRL#3]
To my test, in the function statement as "def cross_modal_contrastive_ctriterion(fea, tau=1.):", values of loss1 and loss2 is qual. 
Then, I have been made some qualitative analysis, and find that loss1 and loss2 are equivalent, just the two multipliers of the numerator have swapped positions. 
Did the approach is redundant?

**Comment by penghu-cs** [comment]
Since sim is a symmetric matrix, it will produce such results. loss1 and loss2 have different physical significance, i.e., Image2Text and Text2Image, thus the code retains loss1 and loss2 to be consistent with the paper.

**Comment by YangYang** [comment]
Your explanation is easy to understand, thanks a lot!
