### ISSUE TITLE
I have two questions for your paper.

### ISSUE THREAD

**Issue by daikitemp** [penghu-cs/MRL#4]
Dear Peng Hu,

I read your paper and it was so impressed. My deepest thanks for providing the code!
I have two questions about your paper.

First, in the Wikipedia dataset, it says that the maximum number of epochs is 100 and the batch-size is 50. However, the github usage says that the maximum number of epochs is 30, and the batch-size is 100. Is it correct to set the maximum number of epochs to 100 and the batch-size to 50?

Second, do the results in your paper report the maximum MAP value throughout all epochs? Or is it the value of MAP in the last epoch?

Sorry to ask this of you when you are busy but I appreciate your help.

Thanks so much.

**Comment by penghu-cs** [comment]
Thanks a lot.
1. Yes, it is correct. You could tune them to achieve better performance.
2. For all methods, we report their results on the testing set when they achieve the best performance on the validation set.

**Comment by daikitemp** [comment]
Thank you for your prompt response.
I understood your answer.

I am truly sorry for disturbing you during a busy time, but thank you for your cooperation.
Thanks you so much!
